### ISSUE TITLE
Модальные окна используются, хотя в readme написано обратное

### ISSUE THREAD

**Issue by Synoecium** [kuzyara/JobsConsole2019.epf#2]
Например, в обработчике команды кнопки "Расписание", есть такая строчка:
    Если Диалог.ОткрытьМодально() Тогда

при этом в readme четко прописано, что используется режим с отказом от модальных окон

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/46853616-36a06200-ce31-11e8-958d-aaf08a8c6b0d.png)
![image](https://user-images.githubusercontent.com/2604430/46853675-60598900-ce31-11e8-8df6-bf8c61e8fc2e.png)
Хм, не вижу. Какая строка?

**Comment by Synoecium** [comment]
да, скачивал старую версию, можно закрывать
